### ISSUE TITLE
Manipulating sprites is broken

### ISSUE THREAD

**Issue by krruzic** [cpp3ds/cpp3ds#7]
I've attached a .3dsx that demonstrates this as well as the emu build. [Here's a link to the code](https://gist.github.com/krruzic/df0c8d2351fde96a5ecc6d5bc8da60ad)

All I did was modify the cpp3ds-template and yeah. Some issues here but I don't know anything about graphics so I have no clue what the problem is. 
[demo.zip](https://github.com/cpp3ds/cpp3ds/files/219092/demo.zip)

**Comment by krruzic** [comment]
Forgot to mention, the emulator build works.

**Comment by Cruel** [comment]
I believe I know the issue. There was a change made in citro3d that I didn't yet put in the Game class. I will commit the changes later today and you can try it again.
