### ISSUE TITLE
Missing vorbis/vorbisfile.h?

### ISSUE THREAD

**Issue by 3xkrazy** [cpp3ds/cpp3ds#9]
I think this file is missing from the master branch. Here's the error output i'm getting:

`mkdir build`
`cd build`
`cmake -DBUILD_EMULATOR=OFF ..`
`-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CTRULIB: /home/hle/.bin/devkitPro/libctru/lib/libctru.a  
-- setting CTRULIB to /home/hle/.bin/devkitPro/libctru/include/..
-- 3dsxtool: /home/hle/.bin/3dsxtool - found
-- smdhtool: /home/hle/.bin/devkitPro/devkitARM/bin/smdhtool - found
-- bannertool: /home/hle/.bin/bannertool - found
-- makerom: /home/hle/.bin/makerom - found
-- strip: /home/hle/.bin/devkitPro/devkitARM/bin/arm-none-eabi-strip - found
-- 3dslink: /home/hle/.bin/devkitPro/devkitARM/bin/3dslink - found
-- Looking for Picasso...
-- Picasso: /home/hle/.bin/devkitPro/devkitARM/bin/picasso - found
-- Looking for nihstro...
-- nihstro: /home/hle/.bin/nihstro-assemble - found
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Found JPEG: /home/hle/.bin/devkitPro/portlibs/armv6k/lib/libjpeg.a  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hle/src/cpp3ds/build
`
...
`[ 31%] Building CXX object src/cpp3ds/Audio/CMakeFiles/cpp3ds-audio.dir/SoundFileFactory.cpp.o
In file included from /home/hle/src/cpp3ds/src/cpp3ds/Audio/SoundFileFactory.cpp:34:0:
/home/hle/src/cpp3ds/include/cpp3ds/Audio/SoundFileReaderOgg.hpp:32:31: fatal error: vorbis/vorbisfile.h: No such file or directory
compilation terminated.
src/cpp3ds/Audio/CMakeFiles/cpp3ds-audio.dir/build.make:230: recipe for target 'src/cpp3ds/Audio/CMakeFiles/cpp3ds-audio.dir/SoundFileFactory.cpp.o' failed
make[2]: *** [src/cpp3ds/Audio/CMakeFiles/cpp3ds-audio.dir/SoundFileFactory.cpp.o] Error 1
CMakeFiles/Makefile2:220: recipe for target 'src/cpp3ds/Audio/CMakeFiles/cpp3ds-audio.dir/all' failed
make[1]: *** [src/cpp3ds/Audio/CMakeFiles/cpp3ds-audio.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by Cruel** [comment]
You need to install the necessarily libs built for the 3ds.

Can be downloaded prebuilt here: https://github.com/cpp3ds/3ds_portlibs/releases

Should be extracted to $DEVKITPRO so that the directory structure like like $DEVKITPRO/portlibs/3ds/(include|libs|etc)
